--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cooldogedev/BuildBattle
build-by-default: true
branches:
- main
projects:
  BuildBattle:
    path: ""
    icon: "assets/icon.png"
    libs:
      - src: cooldogedev/libSQL/libSQL
        version: ^0.1.1
      - src: muqsit/InvMenu/InvMenu
        branch: "4.0"
        version: ^4.4.1
      - src: CortexPE/Commando/Commando
        branch: PM4
        version: ^3.0.0
...

